Add error handling

diff --git a/.github/workflows/data.yml b/.github/workflows/data.yml
--- a/.github/workflows/data.yml
+++ b/.github/workflows/data.yml
@@ -27,8 +27,8 @@ jobs:
           mkdir -p gcp/roles/
           gcloud iam roles list --show-deleted --format json | jq -r '.[]|[.name,(.name | split("/")[-1])] | @tsv' |
           while IFS=$'\t' read -r name shortname; do
-              gcloud iam roles describe "$name" --format json > gcp/roles/$shortname.json
-              echo "Wrote $shortname.json"
+              echo "Writing $shortname.json"
+              gcloud iam roles describe "$name" --format json > gcp/roles/$shortname.json || echo "Failure to write $shortname.json"
           done
           az provider operation list > azure-provider-operations.json
           az role definition list --query '[?roleType == `BuiltInRole`].{assignableScopes: assignableScopes, description: description, permissions: permissions, roleName: roleName, roleType: roleType, type: type}' > azure-built-in-roles.json
